// -> Imports -> Libraries
import { getLocale } from 'next-intl/server';

// -> Imports -> Providers
import { NextIntlClientProvider } from 'next-intl';

// -> Imports -> Components
import HolyLoader from 'holy-loader';

// -> Imports -> Types
import type { Metadata } from 'next';

// -> Imports -> Stylesheets
import '@/cssfiles/globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();
	return (
		<html lang={locale}>
			<body>
				<HolyLoader
					color="linear-gradient(to right, #f12711, #f5af19)"
					height="2px"
					easing="linear"
					showSpinner={false}
				/>
				<NextIntlClientProvider>{children}</NextIntlClientProvider>
			</body>
		</html>
	);
}
